name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: unittest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Build and push Docker image to Google Container Registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.GCP_PROJECT_ID }}.dkr.ecr.${{ secrets.GCP_REGION }}.amazonaws.com/${{ secrets.CLOUD_RUN_SERVICE_NAME }}:latest
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ secrets.CLOUD_RUN_SERVICE_NAME }}
          image: ${{ secrets.pet4all-417123 }}.dkr.ecr.${{ secrets.GCP_REGION }}.amazonaws.com/${{ secrets.CLOUD_RUN_SERVICE_NAME }}:latest
          region: ${{ secrets.GCP_REGION }}